### ISSUE TITLE
Upload / record buttons missing on iOS (chrome and safari)

### ISSUE THREAD

**Issue by jacobrandall** [muxinc/stream.new#157]
Viewing https://stream.new from my iPhone, I'm unable to see the `Record from camera`, `Record my screen` buttons or upload a file from device. I've tried scrolling up and down, left and right, but no luck.

Device: iPhone 14 Pro
Browsers: Chrome and Safari

<img width="687" alt="Screenshot 2023-02-10 at 4 00 32 PM" src="https://user-images.githubusercontent.com/4229502/218224078-fac914e6-aa3f-441e-9aed-35aa8c156911.png">

**Comment by jsanford8** [comment]
thanks, Jacob. We'll take a look and fix this hopefully early next week
