### ISSUE TITLE
3.. 2... 1... *now recording* countdown

### ISSUE THREAD

**Issue by dylanjha** [muxinc/stream.new#23]
Currently, clicking "start recording" will immediately start recording.

Particularly when recording screenshare, this is not great because the first few seconds of every recording is a view of the stream.new UI, usually immediately followed by switching to a different screen.

I think it would be good to have a "3... 2... 1..." countdown whenever recording starts (for both camera recording and screen recording)

**Comment by GeneticGenesis** [comment]
This would be great! 

We should add this repo to hacktoberfest now that it's opt in!

**Comment by erikpena** [comment]
This was implemented in https://github.com/muxinc/stream.new/commit/d86842ace26ded771c3c436bdada5e0b7971367b and is now live!

Enjoy!
