### ISSUE TITLE
iOS 13.3 Safari issue?

### ISSUE THREAD

**Issue by samelie** [muxinc/stream.new#27]
Hi & thanks for this app - looking to use Mux for a web mobile prototype.

Have you been testing iOS? - After 'Upload a video', I don't get navigated to the upload screens.

I've tested iOS safari and Firefox for iOS

Thanks!

**Comment by dylanjha** [comment]
Hi @samelie thanks for reporting.

This is what should happen on iOS - it should open up the file picker menu to browse videos from your camera roll, take a video or browse files on your device

![IMG_8012](https://user-images.githubusercontent.com/764988/95255919-f6350e00-07d6-11eb-81aa-29c98e1fbae1.PNG)

If you don't mind, can you share repro steps, a screen recording or screenshots of what you're seeing. If you're on iPad that will be bigger device dimensions so you might see "Upload a video" / "Record from Camera" / "Record my screen", tapping "Upload a video" should do the same thing as the screenshot above.

Thanks! I'd like to get this fixed if something is not right.

**Comment by samelie** [comment]
I tried to use the desktop Safari devtools -> iPhone but the two have drifted apart in versions so it failed. This was an iPhone 6s

Tested on an iPhone 8 with iOS 13.4.1 and it it's working! 💯 

There must be some missing iOS safari feature in 13.3.1. Wish I could get a stacktrace for you.

**Comment by dylanjha** [comment]
Hmm, so interesting. To confirm, you saw this issue on:

- iPhone 6
- iOS Safari 13.3.1

But iPhone 8 and iOS 13.4.1 worked fine?

Is that correct?

Thank you for following up! 🙌

**Comment by samelie** [comment]
iPhone 6s; that's correct; thanks for condensing.
