### ISSUE TITLE
camera/screenshare is stil active after stop recording

### ISSUE THREAD

**Issue by dylanjha** [muxinc/stream.new#31]
1. allow camera access
1. start recording
1. stop recording
1. [bug] camera is still active indicated by webcam light - it should not be

Same thing happens with screenshare

> skipping recorder stop() b/c state is "inactive"

I think this log line indicates the issue

**Comment by aminamos** [comment]
I noticed that a [reset](https://github.com/aminamos/stream.new/blob/419b98cdbb91c343a6f8317b9ac9c69f35d79adb/components/record-page.tsx#L256) called [hardCleanup()](https://github.com/aminamos/stream.new/blob/419b98cdbb91c343a6f8317b9ac9c69f35d79adb/components/record-page.tsx#L130) which stopped all tracks with [stopUserMedia()](https://github.com/aminamos/stream.new/blob/419b98cdbb91c343a6f8317b9ac9c69f35d79adb/components/record-page.tsx#L94) but [cleanup()](https://github.com/aminamos/stream.new/blob/419b98cdbb91c343a6f8317b9ac9c69f35d79adb/components/record-page.tsx#L107) did not. Adding stopUserMedia() to [stopRecording()](https://github.com/aminamos/stream.new/blob/419b98cdbb91c343a6f8317b9ac9c69f35d79adb/components/record-page.tsx#L328) made the webcam light go away.

Some notes:
- I'm not sure if this change interferes with the [comment](https://github.com/aminamos/stream.new/blob/419b98cdbb91c343a6f8317b9ac9c69f35d79adb/components/record-page.tsx#L200) on lines 200-202
- I only tested this with my Chrome tab's webcam light/audio icon "in use" indicator

**Comment by dylanjha** [comment]
@aminamos thank you! that actually looks like it might be the right fix. If you don't mind can you put in a PR and I can review/qa tomorrow!

Thanks!
