### ISSUE TITLE
Double controls on mobile

### ISSUE THREAD

**Issue by dylanjha** [muxinc/stream.new#41]
1. Open on mobile
2. Tap play - the player opens up into the native iOS full screen player. 
3. Close full screen player
4. See double controls in the UI

![image](https://user-images.githubusercontent.com/764988/99152456-bfb0a580-2656-11eb-804c-15506ee7e263.jpeg)

**Comment by alexdechaves** [comment]
@dylanjha hmm I can't replicate this on my iPhone, just saying

**Comment by dylanjha** [comment]
@alexdechaves huh, it's really easy for me to repro. Did you do the first step of initiating native ios playback, then tapping out of it?

**Comment by alexdechaves** [comment]
Yea no cigar, https://stream.new/v/CfJG77xyOeu00d6cE9PLrIO1DgCin5GdbeFsH00gYmHbQ

Tried Safari and Chrome I'm on iOS 14, so yo no se 💯

**Comment by dylanjha** [comment]
Weird!

https://stream.new/v/dnoOP01It01UqMNjR8dXwnw1z5mg7x2bHPq02pHmpHWZNc

**Comment by erikpena** [comment]
Hey @dylanjha,
with the latest version of stream.new, I'm hoping that the changes to how we playback content may have resolved your issues.  Can you validate it and let us know if you're still seeing the double controls?

**Comment by dylanjha** [comment]
resolved!
