### ISSUE TITLE
Controls are squished/overlapping on mobile

### ISSUE THREAD

**Issue by sstriegs** [muxinc/stream.new#43]
After uploading a vertical video on an iPhone 11 the volume and gear icons are overlapping and the progress circle and time are squished.
![IMG_3282](https://user-images.githubusercontent.com/14186694/99307427-57ef8b80-280b-11eb-9822-7a11d28c04bf.PNG)

https://stream.new/v/jpZnXhZvSWhA7kEnz900HbAmmy1L2nJcJ8hIBJeBdbos

**Comment by alexdechaves** [comment]
This can potentially be solved by something like this:

```
.player {
          --plyr-control-icon-size: ${isVertical ? '10px' : '18px'}
```

Either desktop or mobile, vertical videos could benefit from smaller icons I think. This also opens a can of worms where this player has only one mode. There's no removing controls unless we want to hack it or I'm mistaken.

@dylanjha thoughts?

**Comment by dylanjha** [comment]
@alexdechaves makes sense to me!

>  There's no removing controls unless we want to hack it or I'm mistaken.

I believe you are correct wrt the Plyr APIs, but controls can be hidden with purely css

**Comment by alexdechaves** [comment]
@dylanjha I was wrong we can remove controls in the plyr config, gonna take a stab at it
