### ISSUE TITLE
Super vertical videos are positioned incorrectly

### ISSUE THREAD

**Issue by alexdechaves** [muxinc/stream.new#46]
https://stream.new/v/seK501Bf00kyqSnGdMwQFi3lgqgdoS00qm5PAiV7Yjf2ew

**Comment by erikpena** [comment]
Spoke with @alexdechaves and confirmed that https://github.com/muxinc/stream.new/commit/a49b152907befaec0ae9ed2bf99e19807266dc2b resolved this issue.
