### ISSUE TITLE
macOS Safari recording camera fails

### ISSUE THREAD

**Issue by dylanjha** [muxinc/stream.new#64]
- start camera recording in Safari
- it fails

```
[stream.new]
NotSupportedError: mimeType is not supported
[native code]
(anonymous function) — record-9215b8a9a8ad9eb9c43a.js:1:16393
l — commons.2f484fc1cee4e666eba9.js:1:31248
(anonymous function) — commons.2f484fc1cee4e666eba9.js:1:31033
r — 94d97e5b542eb1ef14fe677c87e30fb345c02fd6.0532e79688b18ec07277.js:1:19610
u — 94d97e5b542eb1ef14fe677c87e30fb345c02fd6.0532e79688b18ec07277.js:1:19814
(anonymous function) — 94d97e5b542eb1ef14fe677c87e30fb345c02fd6.0532e79688b18ec07277.js:1:19873
Promise
(anonymous function) — 94d97e5b542eb1ef14fe677c87e30fb345c02fd6.0532e79688b18ec07277.js:1:19764
p — record-9215b8a9a8ad9eb9c43a.js:1:9132
```

**Comment by jaredsmith** [comment]
I'm seeing the same thing on my side.

**Comment by dylanjha** [comment]
This looks suspicious

https://github.com/muxinc/stream.new/blob/main/components/record-page.tsx#L298-L309


* the comment `"good thing safari supports the preferredOptions"` 🤔  does it, though?
* and looks like `MediaRecorder.isTypeSupported` is a function in safari now
* I'm suspecting something in Safari changed recently

**Comment by damechen** [comment]
Looks like these two mimeTypes are not supported on Safari https://jsfiddle.net/0v4cw6na/

```
const preferredOptions = { mimeType: 'video/webm;codecs=vp9' };
const backupOptions = { mimeType: 'video/webm;codecs=vp8,opus' };
```

**Comment by jaredsmith** [comment]
That's my understanding as well -- Safari only supports `video/mp4` and `video/mp4;codecs=avc1` mime types for video, and `audio/mp4` and `audio/mp4;codecs=aac` mime types for audio.

**Comment by heff** [comment]
Just ran into this myself. Does Safari only supporting those types mean we can't fix this, or need to change some configuration?
