### ISSUE TITLE
Poor resolution while doing recording from iPhone

### ISSUE THREAD

**Issue by damechen** [muxinc/stream.new#67]
Tried to record a video from my iPhone 12 Pro, but the video resolution is degraded.

**Comment by dylanjha** [comment]
@damechen interesting. When you record on iPhone, stream.new should be launching iOS's native camera. In which case the iPhone is in full control of what gets recorded.

When you say the video resolution is poor, is that on the playback side? I'm wondering if maybe there are higher bitrates available but when you played the video back, you were on one of the lower bitrates.

Can you link to an example of a video you recorded on your iPhone that had this issue?

**Comment by damechen** [comment]
The camera live preview has a poor resolution. Also when the video is recorded, the playback resolution is bad too. If it's iOS's native camera, does MediaRecorder API still take effect? I'm wondering if there is any setting from MediaRecorder to set a higher frame rate and larger width & height.

Here is my screen recording: https://stream.new/v/02Nm9XJnjke500nntpHwupyAo8BUu8yT6dob3KILO5kow
Here is a video recorded from the rear camera on iPhone 12 Pro: https://stream.new/v/yiCsRJYv3r1rvLGR5rkT1l8sqRSXHalb6yUpokG31MA

**Comment by dylanjha** [comment]
> If it's iOS's native camera, does MediaRecorder API still take effect?

No, on iOS media recorder is not used. The native iOS functionality takes over for recording or selecting an already recorded file from the camera roll.

> Here is a video recorded from the rear camera on iPhone 12 Pro: https://stream.new/v/yiCsRJYv3r1rvLGR5rkT1l8sqRSXHalb6yUpokG31MA

You're totally right about this one, checking the manifest, there is a `RESOLUTION=360x480` and `RESOLUTION=270x360`.

Digging more into this, and it gets pretty interesting (I wasn't aware of this until now). There's two paths on iOS:

1. "Add video" > "Photo Library" - this opens the camera roll to select a video that was already recorded
2. "Add video" > "Upload Photo or Video" - this launches the iOS camera, record and upload

![IMG_27568C0B9A65-1](https://user-images.githubusercontent.com/764988/120751190-70c84180-c4bc-11eb-98ea-8b5664b1faff.jpeg)

The quality of the video for (1) is based on the camera capture settings of the device:

![IMG_8782](https://user-images.githubusercontent.com/764988/120751340-b6850a00-c4bc-11eb-88d8-cb6fa690a569.jpg)

But the quality when selecting (2) will actually be way different. It appears that when going down this path the resolution of the recorded video is *always* 360x480. That's kind of weird, and honestly not what I expected but I found evidence of other people running into this:

* [apple forum](https://developer.apple.com/forums/thread/31655)
* [blog post](https://blog.addpipe.com/video-quality-when-recording-videos-from-safari-on-ios-through-html-media-capture/)

Digging around to find more of an official documentation about this, but wasn't able to easily find that.

Ultimately, when going down either of these paths on iOS, MediaRecorder is not involved. All stream.new does here is take the file that iOS supplies and uploads it to Mux.

**Comment by damechen** [comment]
Thank you @dylanjha! I also did a lot of research today and found out the same, here is another evidence, sigh
https://stackoverflow.com/a/44101197/2498993

**Comment by dylanjha** [comment]
Closing this for now because as far as I can tell it is entirely controlled by iOS. As a general rule, it's better video quality to record on devices, and then select use option (1) to select the video off the camera roll.

Thanks for opening this so that other folks may find it!
